# -*- coding: utf-8 -*-
"""Derivative application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ax3t7ZZZEx_5MzXDq3C1R4ATKDkxnKPM
"""

6x^2+2*x-10

der = lambda x : 12*x+2

y = lambda x : 4* x**4- 6 * x**3 -2* x**2 - 2*x + 10

der = lambda x : 16 * x**3 - 18 * x**2 - 4*x - 2

der(5)

lr = 0.001
cur_x = 5
change = 1
iteration = 1
while change>0.000000000001:
  prev_x = cur_x
  cur_x = cur_x - der(cur_x)*lr
  change = prev_x - cur_x
  iteration += 1
  #print(change)

cur_x

y(cur_x)

cost_buiscuit = lambda x : 2500 - 10*x -0.01* x**2 +0.0002* x**3

der_cost_buis = lambda x : -10 - 0.02 * x + 0.0006 * x**2

lr = 0.001
cur_x = 500
change = 1
iteration = 1
while change>0.000000000001:
  prev_x = cur_x
  cur_x = cur_x - der_cost_buis(cur_x)*lr
  change = prev_x - cur_x
  iteration += 1
  #print(change)

cur_x

cost_buiscuit(cur_x)

cost_buiscuit(200)

cost_buiscuit(300)

cost_buiscuit(146.83)

cost_buiscuit(100)

y = 20 + 3x + 2x^2 + 4x^3

Find minimal value of y given an x

1. start from a random number
2. select the learninig rate 

3. find the direction - dervative
4. find the new number you are at by negative the old place to new place