# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-C_3irUO4Vauy9vdhJcUnnVk7SFtvK8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.preprocessing import StandardScaler, MinMaxScaler



data = pd.read_csv("https://raw.githubusercontent.com/nursnaaz/25DaysInMachineLearning/master/18%20-%20Day%20-%2018%20-%20Linear%20Regression%20Practise%20Python/USA_Housing.csv")

data.head()

data.info()

data.describe().T

data.duplicated().sum()

data.isnull().sum()

data.drop(columns="Address", inplace = True)

data.head()

data.drop(columns = "Price").boxplot()

sns.pairplot(data)

data.corr()

sns.heatmap(data.corr(), annot=True)

#variance inflation factor - VIF

X = data.drop(columns = "Price")
  
# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
  
# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
  
print(vif_data)

vif_data[vif_data['VIF']>30]['feature'].values

X = data[['Avg. Area Income']]
y = data['Price']

train_X, test_X, train_y, test_y = train_test_split(X,y,test_size = 0.3, random_state=2)

train_X.shape, test_X.shape, train_y.shape, test_y.shape

model = LinearRegression()

model.fit(train_X,train_y)

model.coef_

model.intercept_

#House Price = 21.28 * Income - 227466.46

plt.scatter(train_X, train_y)
plt.plot(train_X, 21.28*train_X - 227466.46 )

plt.scatter(test_X, test_y)
plt.plot(test_X, 21.28*test_X - 227466.46 )

"""y              ypred


error = y -  ypred



MSE = Mean Square Error

summation(error^2)/number of sample


MAE = Mean Absolute Error

summation(|error|)/number of sample


Root mean square error

sqrt(summation(error)^2/n)


Mean Absolute percentage error

summation((|y-ypred|)/y)/n)*100


"""

train_pred = model.predict(train_X)

train_pred

train_mse = mean_squared_error(train_y, train_pred)

train_mae = mean_absolute_error(train_y, train_pred)

train_rmse = np.sqrt(mean_squared_error(train_y, train_pred))

train_mape = mean_absolute_percentage_error(train_y, train_pred)

test_pred = model.predict(test_X)

test_mse = mean_squared_error(test_y, test_pred)

test_mae = mean_absolute_error(test_y, test_pred)

test_rmse = np.sqrt(mean_squared_error(test_y, test_pred))

test_mape = mean_absolute_percentage_error(test_y, test_pred)



train_mse, train_mae, train_rmse, train_mape

test_mse, test_mae, test_rmse, test_mape

model.predict([['5000000']])[0]







scale = StandardScaler()
X = pd.DataFrame(scale.fit_transform(data.drop(columns='Price')), columns = data.drop(columns='Price').columns)

X

#X = data.drop(columns='Price')
y = data['Price']

X

train_X, test_X, train_y, test_y = train_test_split(X,y,test_size = 0.3, random_state=2)

test_X

train_X.shape, test_X.shape, train_y.shape, test_y.shape

model = LinearRegression()

model.fit(train_X,train_y)

model.coef_

model.intercept_

2.44393333e+03

#House Price = 21.28 * Income + 165018.739 * HouseAge + 119428.612*rooms + 2.44393333e+03*bedroom + 
#15.1 *population - 2623728.373509867

train_pred = model.predict(train_X)

train_pred

train_mse = mean_squared_error(train_y, train_pred)

train_mae = mean_absolute_error(train_y, train_pred)

train_rmse = np.sqrt(mean_squared_error(train_y, train_pred))

train_mape = mean_absolute_percentage_error(train_y, train_pred)

test_pred = model.predict(test_X)

test_mse = mean_squared_error(test_y, test_pred)

test_mae = mean_absolute_error(test_y, test_pred)

test_rmse = np.sqrt(mean_squared_error(test_y, test_pred))

test_mape = mean_absolute_percentage_error(test_y, test_pred)



train_mse, train_mae, train_rmse, train_mape

test_mse, test_mae, test_rmse, test_mape



train_mse, train_mae, train_rmse, train_mape

test_mse, test_mae, test_rmse, test_mape

model.predict([['5000000']])[0]



